### ISSUE TITLE
Add UUIDs

### ISSUE THREAD

**Issue by stam** [mmzsource/tankbattle#1]
On the frontend I would like to keep track of assets (tanks/lasers/explosions) and not delete and recreate them every tick for performance reasons.

Tanks currently have IDs, but they are not unique, if a tank is killed and a new tank joins, they get the same ID but they are not the same instance. (movement between a killed tank and a newly joined tank in the next tick should not be animated).

Add UUIDs for unique instances of lasers/trees/tanks/explosions

**Comment by mmzsource** [comment]
Done: https://github.com/mmzsource/tankbattle/commit/332469679b23cdebbf90fa03acb9bf1702ff4085
